export const login: string
export const loginWrapper: string
export const loginLeft: string
export const loginRight: string
export const loginLogo: string
export const loginDesc: string
export const loginBox: string
export const field: string
export const fieldLabel: string
export const loginInput: string
export const loginButton: string
export const loginForgot: string
export const loginRegisterButton: string