export const createPost: string
export const createPostContainer: string
export const profileImg: string
export const createPostContent: string
export const activePostContent: string
export const createPostInput: string
export const createPostDivision: string
export const createPostBotbar: string
export const createPostButton: string