export const profile: string
export const profileRight: string
export const profileCover: string
export const profileCoverImg: string
export const profileUserImg: string
export const profileInfo: string
export const profileInfoName: string
export const profileInfoDesc: string
export const profileRightBottom: string