export const post: string
export const postContainer: string
export const postTopbar: string
export const postImg: string
export const postProfileImg: string
export const postUsername: string
export const postDate: string
export const postOptions: string
export const postContent: string
export const postContentText: string
export const postReadMore: string
export const postReadLess: string
export const postContentImg: string
export const postBotbar: string
export const postComments: string
export const postReactionList: string
export const postReactionItem: string
export const postLikeCounter: string
export const postCommentCounter: string