export const signup: string
export const signupWrapper: string
export const signupLeft: string
export const signupRight: string
export const signupLogo: string
export const signupDesc: string
export const signupBox: string
export const fieldLabel: string
export const signupInput: string
export const signupButton: string
export const signupForgot: string
export const signupRegisterButton: string